Removed limit=num, num is currently unused due to bug in pylast
  File "/usr/local/lib/python2.7/dist-packages/pylast/__init__.py", line 4035, in _collect_nodes
    if main.hasAttribute("totalPages"):
AttributeError: Text instance has no attribute 'hasAttribute'